### ISSUE TITLE
关于二手网站

### ISSUE THREAD

**Issue by LeiureTime** [Resulte/Second-Market#1]
您好，我是一个想要学习django的人，下载了您的代码。可是我发现，您的代码文件已经打开，不算是一个django项目存在在pycharm里。
即便是我自己创建一个django项目，然后将您的文件导入，便立马从django变成了普通python文件运行模式。
不知您可否给一个解决方法。
![image](https://user-images.githubusercontent.com/105108558/167294707-b2e8580d-7eea-4362-a846-e19e99b1d375.png)

下面是正常的运行图。
![image](https://user-images.githubusercontent.com/105108558/167294735-ea880923-cf2d-4298-bd64-19f0d7992b49.png)

**Comment by Resulte** [comment]
@LeiureTime 请确保你的django 版本是1.10

**Comment by LeiureTime** [comment]
> @LeiureTime 请确保你的django 版本是1.10
再次打扰您一下。
我把代码下载下来之后，我更改文件名为cucmarket。
这个错误，我搜了好久没法解决。如果我能解决的问题绝不打扰您，深感抱歉！
![image](https://user-images.githubusercontent.com/105108558/167301981-0bf089b1-74ad-4652-bb6c-593b14426006.png)

**Comment by Resulte** [comment]
@LeiureTime 你直接从第二个cucmarket文件夹打开项目呢
![167301981-0bf089b1-74ad-4652-bb6c-593b14426006](https://user-images.githubusercontent.com/34178764/167302427-f58f36f0-e78d-4bf6-895c-04cede7e52c7.png)
