### ISSUE TITLE
大佬，这是什么情况啊

### ISSUE THREAD

**Issue by villain-bluecat** [Resulte/Second-Market#2]
![KXHJBGR}R1 6REW %MEG3](https://user-images.githubusercontent.com/98535180/192414252-ae28974a-70e0-40f2-bc0c-bf119b9d7879.png)

**Comment by Resulte** [comment]
不要放在中文目录下。或者可以尝试改一下导入的包路径

**Comment by villain-bluecat** [comment]
![image](https://user-images.githubusercontent.com/98535180/192424733-7dfdf4e9-d0d9-4d1a-b74d-1d384f24384d.png)
佬，我在终端运行，又出现这个问题了

**Comment by Resulte** [comment]
确认一下manage.py是否在你当前运行的目录下
